services:
  theme_debug:
    class: Drupal\Console\Command\Theme\DebugCommand
    tags:
      - { name: console.command }
  theme_download:
    class: Drupal\Console\Command\Theme\DownloadCommand
    tags:
      - { name: console.command }